services:
  - type: web
    name: n8n
    env: node
    repo: https://github.com/gzhumurova/n8n-on-render
    plan: free
    buildCommand: 'echo "skip build"'
    startCommand: 'sh start.sh'
    envVars:
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 10000
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: admin123
